name: Deploy with Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy on EC2
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies & build
        run: |
          npm install
          npm run build

      - name: Restart server
        run: |
          pm2 restart nest-api
